### ISSUE TITLE
add share buttons to top of page

### ISSUE THREAD

**Issue by daybowbow** [technologists-for-progress/52calls-52weeks#78]
In addition to the footer buttons, can we add Fb buttons to hero somehow (either in header or under hero copy - use your design eye to see what looks best here)

**Comment by daybowbow** [comment]
@voxmatt @blake213 @jgallen23 any chance any of you can get to this in the next day or two? We really want to get the share up more prominent on the page. Will take some tinkering to see what looks best (either in the nav (we can remove "Home" since it's basically useless) or under the hero sub-copy) . 

Ideally has some context. If under sub-header - potential copy: "Change happens one person at a time. Pass it on!" [buttons]

If in nav, can context copy look good? (Spread the word! like in footer) If not, just the buttons.

**Comment by blake213** [comment]
These buttons don't work very well in the hero/header. In my opinion, they distract from the call to action, which is the signup form. I went with placing them below the introduction paragraph, and it feels like it works well with the contextual copy.

Fixed in this commit: https://github.com/technologists-for-progress/callsforchange/commit/28aa525b3bf4b6ecfb3525cab60c748b73b1ee43
